# Generated by Django 3.2.19 on 2023-06-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_temps', '0003_auto_20230628_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=100)),
                ('day', models.CharField(choices=[('Monday', 'Lundi'), ('Tuesday', 'Mardi'), ('Wednesday', 'Mercredi'), ('Thursday', 'Jeudi'), ('Friday', 'Vendredi'), ('Saturday', 'Samedi')], max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('professor', models.CharField(max_length=100)),
                ('classroom', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('credit_hours', models.IntegerField()),
                ('info', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
