# Generated by Django 3.2.19 on 2023-06-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_temps', '0005_auto_20230629_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploidutemps',
            name='info',
            field=models.TextField(blank=True, default='-'),
        ),
    ]
