# Generated by Django 3.2.19 on 2023-06-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_temps', '0007_emploidutemps_l2'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiDuTemps_l3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=20)),
                ('cours', models.CharField(max_length=200)),
                ('heure', models.CharField(max_length=20)),
                ('professeur', models.CharField(max_length=100)),
                ('salle', models.CharField(max_length=50)),
                ('groupe', models.CharField(max_length=50)),
                ('masse_horaire', models.CharField(max_length=50)),
                ('info', models.TextField(blank=True, default='-')),
            ],
        ),
    ]
